export const paths = {
  home: '/',
  products: '/productos',
  productDetail: (slug: string) => `/productos/${slug}`,
  categories: '/categorias',
  categoryDetail: (slug: string) => `/categorias/${slug}`,
  services: '/servicios',
  serviceDetail: (slug: string) => `/servicios/${slug}`,
  about: '/nosotros',
  faq: '/preguntas-frecuentes',
  contact: '/contacto',
  privacy: '/politica-de-privacidad',
  terms: '/terminos-y-condiciones',
  notFound: '/404',
} as const;
